server:
  port: 8090

spring:
    datasource:
        url: jdbc:mysql://172.18.0.4:3306/bgsystem
        username: root
        password: Zhzhd@#1106
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        logSlowSql: true
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
          host: 127.0.0.1
          port : 6379
          timeout : 1800
          password :
          dbIndex : 0
          expiration: 3000
          maxIdle : 300
          maxActive : 600
          maxWait : 1000
          testOnborrow : true
    thymeleaf:
      prefix: classpath:templates/
      check-template-location: true
      cache: false
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      servlet:
        content-type: text/html
      enabled: true
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
#      static-locations: classpath:static/
    mvc:
      static-path-pattern: /**
    mail:
      port: 25
      host: smtp.qq.com
      username: 562599006@qq.com
      password: bmjniikrykcvbchd
      protocol: smtp
      default-encoding: UTF-8
      properties:
              mail:
                smtp:
                  auth: true
                  starttls:
                    enable: true
                    required: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zhzhd.bgsystem.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


#日志配置
logging:
  config: classpath:logging-config.xml

#网站域名
domain: zhangzhendong.cn

